name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Venus Tools
          GIT_AUTHOR_EMAIL: tools@venus.io
          GIT_COMMITTER_NAME: Venus Tools
          GIT_COMMITTER_EMAIL: tools@venus.io
        run: yarn semantic-release
